import { NetworkPluginID, TokenType } from '@/constants/enum.js';
import { getEvmNativeTokenAddress } from '@/providers/ethereum/getNativeTokenAddress.js';
import CHAINS from '@/web3-constants/evm/chains.json' with { type: 'json' };
import type { ChainDescriptor, NetworkDescriptor } from '@/web3-shared/base/specs.js';
import { EthereumChainId, EthereumNetworkType, EthereumSchemaType } from '@/web3-shared/evm/types.js';

const PLUGIN_ID = NetworkPluginID.PLUGIN_EVM;

export const NETWORK_DESCRIPTORS: ReadonlyArray<NetworkDescriptor<EthereumChainId, EthereumNetworkType>> = [
    {
        ID: `${PLUGIN_ID}_ethereum`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Mainnet,
        type: EthereumNetworkType.Ethereum,
        name: 'Ethereum',
        shortName: 'ETH',
        icon: '/image/chains/ethereum.png',
        iconColor: 'rgb(28, 104, 243)',
        averageBlockDelay: 10,
        backgroundGradient:
            'linear-gradient(180deg, rgba(98, 126, 234, 0.15) 0%, rgba(98, 126, 234, 0.05) 100%), rgba(255, 255, 255, 0.2)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_bsc`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.BSC,
        type: EthereumNetworkType.Binance,
        name: 'BNB Chain',
        icon: '/image/chains/binance.png',
        iconColor: 'rgb(240, 185, 10)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(243, 186, 47, 0.15) 0%, rgba(243, 186, 47, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_base`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Base,
        type: EthereumNetworkType.Base,
        name: 'Base',
        icon: '/image/chains/base.png',
        iconColor: 'rgb(0, 82, 255)',
        backgroundGradient: 'linear-gradient(180deg, rgba(130, 71, 229, 0.15) 0%, rgba(130, 71, 229, 0.05) 100%)',
        averageBlockDelay: 10,
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_polygon`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Polygon,
        type: EthereumNetworkType.Polygon,
        name: 'Polygon',
        icon: '/image/chains/polygon.png',
        iconColor: 'rgb(119, 62, 225)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(130, 71, 229, 0.15) 0%, rgba(130, 71, 229, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_arbitrum`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Arbitrum,
        type: EthereumNetworkType.Arbitrum,
        name: 'Arbitrum One',
        shortName: 'Arbitrum',
        icon: '/image/chains/arbitrum.png',
        iconColor: 'rgb(36, 150, 238)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(40, 160, 240, 0.15) 0%, rgba(40, 160, 240, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_xdai`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.xDai,
        type: EthereumNetworkType.xDai,
        name: 'Gnosis',
        icon: '/image/chains/xdai.png',
        iconColor: 'rgb(73, 169, 166)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(72, 168, 166, 0.15) 0%, rgba(72, 168, 166, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_scroll`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Scroll,
        type: EthereumNetworkType.Scroll,
        name: 'Scroll',
        icon: 'https://static.debank.com/image/chain/logo_url/scrl/1fa5c7e0bfd353ed0a97c1476c9c42d2.png',
        backgroundGradient:
            'linear-gradient(180deg, rgba(98, 126, 234, 0.15) 0%, rgba(98, 126, 234, 0.05) 100%), rgba(255, 255, 255, 0.2)',
        iconColor: 'rgb(255, 248, 243)',
        averageBlockDelay: 9,
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_avalanche`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Avalanche,
        type: EthereumNetworkType.Avalanche,
        name: 'Avalanche',
        shortName: 'AVAX',
        icon: '/image/chains/avalanche.png',
        backgroundGradient: 'linear-gradient(180deg, rgba(232, 65, 66, 0.15) 0%, rgba(232, 65, 66, 0.05) 100%)',
        iconColor: 'rgb(232, 65, 66)',
        averageBlockDelay: 10,
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_aurora`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Aurora,
        type: EthereumNetworkType.Aurora,
        name: 'Aurora',
        icon: '/image/chains/aurora.png',
        iconColor: 'rgb(112, 212, 74)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(112, 212, 75, 0.15) 0%, rgba(112, 212, 75, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_conflux`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Conflux,
        type: EthereumNetworkType.Conflux,
        name: 'Conflux',
        icon: '/image/chains/conflux.png',
        iconColor: 'rgb(112, 212, 74)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(72, 168, 166, 0.15) 0%, rgba(72, 168, 166, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_fantom`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Fantom,
        type: EthereumNetworkType.Fantom,
        name: 'Fantom',
        icon: '/image/chains/fantom.png',
        iconColor: 'rgb(73, 169, 166)',
        averageBlockDelay: 10,
        backgroundGradient: 'linear-gradient(180deg, rgba(24, 94, 255, 0.15) 0%, rgba(24, 94, 255, 0.05) 100%)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_optimism`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Optimism,
        type: EthereumNetworkType.Optimism,
        name: 'Optimism',
        icon: '/image/chains/optimism.png',
        iconColor: 'rgb(232, 65, 66)',
        backgroundGradient: 'linear-gradient(180deg, rgba(232, 65, 66, 0.15) 0%, rgba(232, 65, 66, 0.05) 100%)',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_metis`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Metis,
        type: EthereumNetworkType.Metis,
        icon: 'https://static.debank.com/image/chain/logo_url/metis/7485c0a61c1e05fdf707113b6b6ac917.png',
        iconColor: 'rgb(36, 150, 238)',
        backgroundGradient: 'linear-gradient(180deg, rgba(130, 71, 229, 0.15) 0%, rgba(130, 71, 229, 0.05) 100%)',
        name: 'Metis',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_xlayer`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.XLayer,
        type: EthereumNetworkType.XLayer,
        icon: '/image/chains/xlayer.png',
        iconColor: 'rgb(255, 255, 255)',
        name: 'X Layer',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_zora`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Zora,
        type: EthereumNetworkType.Zora,
        icon: 'https://static.debank.com/image/chain/logo_url/zora/de39f62c4489a2359d5e1198a8e02ef1.png',
        iconColor: '#3059AE',
        name: 'Zora',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_celo`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Celo,
        type: EthereumNetworkType.Celo,
        icon: '/image/chains/celo.png',
        iconColor: '#FCFF52',
        name: 'Celo',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_zksync_era`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.ZksyncEra,
        type: EthereumNetworkType.ZksyncEra,
        icon: '/image/chains/zksync.png',
        iconColor: '#3059AE',
        name: 'Zksync Era',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_linea`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Linea,
        type: EthereumNetworkType.Linea,
        icon: '/image/chains/linea.png',
        iconColor: '#3059AE',
        name: 'Linea',
        isMainnet: true,
        averageBlockDelay: 10,
    },
    {
        ID: `${PLUGIN_ID}_plasma`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: EthereumChainId.Plasma,
        type: EthereumNetworkType.Plasma,
        icon: '/image/chains/plasma.png',
        iconColor: '#3059AE',
        name: 'Plasma',
        isMainnet: true,
        averageBlockDelay: 10,
    },
];

export const CHAIN_DESCRIPTORS: ReadonlyArray<
    ChainDescriptor<EthereumChainId, EthereumSchemaType, EthereumNetworkType>
> = CHAINS.map((x) => {
    const network = NETWORK_DESCRIPTORS.find((y) => y.chainId === x.chainId);
    return {
        ...x,
        ID: `${x.chainId}_${x.name}`,
        coinMarketCapChainId: '',
        coinGeckoChainId: '',
        coinGeckoPlatformId: '',
        type: (x.type as EthereumNetworkType | undefined) || EthereumNetworkType.Ethereum,
        color: network?.iconColor || x.color || 'rgb(138, 138, 138)',
        nativeCurrency: {
            id: getEvmNativeTokenAddress(x.chainId),
            address: getEvmNativeTokenAddress(x.chainId),
            type: TokenType.Fungible,
            schema: EthereumSchemaType.Native,
            ...x.nativeCurrency,
        },
        // not accessible
        rpcUrl: '',
        iconUrl: network?.icon || x.nativeCurrency.logoURL,
        explorerUrl: {
            url: x.explorers?.[0]?.url || x.infoURL,
        },
        isCustomized: false,
    };
});
