export interface PolymarketGammaImageOptimized {
    id?: string;
    imageUrlSource?: string;
    imageUrlOptimized?: string;
    imageSizeKbSource?: number;
    imageSizeKbOptimized?: number;
    imageOptimizedComplete?: boolean;
    imageOptimizedLastUpdated?: string;
    relID?: number;
    field?: string;
    relname?: string;
}

/**
 * Gamma "Get event by slug" response shape.
 * Doc: https://docs.polymarket.com/api-reference/events/get-event-by-slug
 */
export interface PolymarketGammaEvent {
    id?: string;
    ticker?: string | null;
    slug?: string | null;
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    resolutionSource?: string | null;
    startDate?: string | null;
    creationDate?: string | null;
    endDate?: string | null;
    image?: string | null;
    icon?: string | null;
    active?: boolean | null;
    closed?: boolean | null;
    archived?: boolean | null;
    new?: boolean | null;
    featured?: boolean | null;
    restricted?: boolean | null;
    liquidity?: number | null;
    volume?: number | null;
    openInterest?: number | null;
    sortBy?: string | null;
    category?: string | null;
    subcategory?: string | null;
    isTemplate?: boolean | null;
    templateVariables?: string | null;
    published_at?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    commentsEnabled?: boolean | null;
    competitive?: number | null;
    volume24hr?: number | null;
    volume1wk?: number | null;
    volume1mo?: number | null;
    volume1yr?: number | null;
    featuredImage?: string | null;
    disqusThread?: string | null;
    parentEvent?: string | null;
    enableOrderBook?: boolean | null;
    liquidityAmm?: number | null;
    liquidityClob?: number | null;
    negRisk?: boolean | null;
    negRiskMarketID?: string | null;
    negRiskFeeBips?: number | null;
    commentCount?: number | null;
    imageOptimized?: PolymarketGammaImageOptimized;
    iconOptimized?: PolymarketGammaImageOptimized;
    featuredImageOptimized?: PolymarketGammaImageOptimized;
    subEvents?: string[] | null;
    markets?: PolymarketGammaMarket[];
    tags?: PolymarketGammaTag[];
    cyom?: boolean | null;
    closedTime?: string | null;
    showAllOutcomes?: boolean | null;
    showMarketImages?: boolean | null;
    automaticallyResolved?: boolean | null;
    enableNegRisk?: boolean | null;
    automaticallyActive?: boolean | null;
    eventDate?: string | null;
    startTime?: string | null;
    eventWeek?: number | null;
    seriesSlug?: string | null;
    score?: string | null;
    elapsed?: string | null;
    period?: string | null;
    live?: boolean | null;
    ended?: boolean | null;
    finishedTimestamp?: string | null;
    gmpChartMode?: string | null;
    eventCreators?: Array<{
        id?: string;
        creatorName?: string;
        creatorHandle?: string;
        creatorUrl?: string;
        creatorImage?: string;
        createdAt?: string;
        updatedAt?: string;
    }>;
    tweetCount?: number | null;
    chats?: Array<{
        id?: string;
        channelId?: string;
        channelName?: string;
        channelImage?: string;
        live?: boolean;
        startTime?: string;
        endTime?: string;
    }>;
    featuredOrder?: number | null;
    estimateValue?: boolean | null;
    cantEstimate?: boolean | null;
    estimatedValue?: string | null;
    templates?: Array<{
        id?: string;
        eventTitle?: string;
        eventSlug?: string;
        eventImage?: string;
        marketTitle?: string;
        description?: string;
        resolutionSource?: string;
        negRisk?: boolean;
        sortBy?: string;
        showMarketImages?: boolean;
        seriesSlug?: string;
        outcomes?: string;
    }>;
    spreadsMainLine?: number | null;
    totalsMainLine?: number | null;
    carouselMap?: string | null;
    pendingDeployment?: boolean | null;
    deploying?: boolean | null;
    deployingTimestamp?: string | null;
    scheduledDeploymentTimestamp?: string | null;
    gameStatus?: string | null;
}

export interface PolymarketGammaTag {
    id?: string;
    label?: string;
    slug?: string;
    forceShow?: boolean;
    publishedAt?: string;
    createdBy?: number;
    updatedBy?: number;
    createdAt?: string;
    updatedAt?: string;
    forceHide?: boolean;
    isCarousel?: boolean;
}

/**
 * Gamma "Get market by slug" response shape.
 * Doc: https://docs.polymarket.com/api-reference/markets/get-market-by-slug
 */
export interface PolymarketGammaMarket {
    id?: string;
    question?: string | null;
    conditionId: string;
    slug?: string | null;
    twitterCardImage?: string | null;
    resolutionSource?: string | null;
    endDate?: string | null;
    category?: string | null;
    ammType?: string | null;
    liquidity?: string | null;
    sponsorName?: string | null;
    sponsorImage?: string | null;
    startDate?: string | null;
    xAxisValue?: string | null;
    yAxisValue?: string | null;
    denominationToken?: string | null;
    fee?: string | null;
    image?: string | null;
    icon?: string | null;
    lowerBound?: string | null;
    upperBound?: string | null;
    description?: string | null;
    outcomes?: string | null;
    outcomePrices?: string | null;
    volume?: string | null;
    active?: boolean | null;
    marketType?: string | null;
    formatType?: string | null;
    lowerBoundDate?: string | null;
    upperBoundDate?: string | null;
    closed?: boolean | null;
    marketMakerAddress?: string;
    createdBy?: number | null;
    updatedBy?: number | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    closedTime?: string | null;
    wideFormat?: boolean | null;
    new?: boolean | null;
    mailchimpTag?: string | null;
    featured?: boolean | null;
    archived?: boolean | null;
    resolvedBy?: string | null;
    restricted?: boolean | null;
    marketGroup?: number | null;
    groupItemTitle?: string | null;
    groupItemThreshold?: string | null;
    questionID?: string | null;
    umaEndDate?: string | null;
    enableOrderBook?: boolean | null;
    orderPriceMinTickSize?: number | null;
    orderMinSize?: number | null;
    umaResolutionStatus?: string | null;
    curationOrder?: number | null;
    volumeNum?: number | null;
    liquidityNum?: number | null;
    endDateIso?: string | null;
    startDateIso?: string | null;
    umaEndDateIso?: string | null;
    hasReviewedDates?: boolean | null;
    readyForCron?: boolean | null;
    commentsEnabled?: boolean | null;
    volume24hr?: number | null;
    volume1wk?: number | null;
    volume1mo?: number | null;
    volume1yr?: number | null;
    gameStartTime?: string | null;
    secondsDelay?: number | null;
    clobTokenIds?: string | null;
    disqusThread?: string | null;
    shortOutcomes?: string | null;
    teamAID?: string | null;
    teamBID?: string | null;
    umaBond?: string | null;
    umaReward?: string | null;
    fpmmLive?: boolean | null;
    volume24hrAmm?: number | null;
    volume1wkAmm?: number | null;
    volume1moAmm?: number | null;
    volume1yrAmm?: number | null;
    volume24hrClob?: number | null;
    volume1wkClob?: number | null;
    volume1moClob?: number | null;
    volume1yrClob?: number | null;
    volumeAmm?: number | null;
    volumeClob?: number | null;
    liquidityAmm?: number | null;
    liquidityClob?: number | null;
    makerBaseFee?: number | null;
    takerBaseFee?: number | null;
    customLiveness?: number | null;
    acceptingOrders?: boolean | null;
    notificationsEnabled?: boolean | null;
    score?: number | null;
    imageOptimized?: PolymarketGammaImageOptimized;
    iconOptimized?: PolymarketGammaImageOptimized;
    events?: PolymarketGammaEvent[];
    tags?: PolymarketGammaTag[];
    creator?: string | null;
    ready?: boolean | null;
    funded?: boolean | null;
    pastSlugs?: string | null;
    readyTimestamp?: string | null;
    fundedTimestamp?: string | null;
    acceptingOrdersTimestamp?: string | null;
    competitive?: number | null;
    rewardsMinSize?: number | null;
    rewardsMaxSpread?: number | null;
    spread?: number | null;
    automaticallyResolved?: boolean | null;
    oneDayPriceChange?: number | null;
    oneHourPriceChange?: number | null;
    oneWeekPriceChange?: number | null;
    oneMonthPriceChange?: number | null;
    oneYearPriceChange?: number | null;
    lastTradePrice?: number | null;
    bestBid?: number | null;
    bestAsk?: number | null;
    automaticallyActive?: boolean | null;
    clearBookOnStart?: boolean | null;
    chartColor?: string | null;
    seriesColor?: string | null;
    showGmpSeries?: boolean | null;
    showGmpOutcome?: boolean | null;
    manualActivation?: boolean | null;
    negRiskOther?: boolean | null;
    gameId?: string | null;
    groupItemRange?: string | null;
    sportsMarketType?: string | null;
    line?: number | null;
    umaResolutionStatuses?: string | null;
    pendingDeployment?: boolean | null;
    deploying?: boolean | null;
    deployingTimestamp?: string | null;
    scheduledDeploymentTimestamp?: string | null;
    rfqEnabled?: boolean | null;
    eventStartTime?: string | null;
}
