/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155 } from './ERC1155.js';
export type { ERC165 } from './ERC165.js';
export type { ERC20 } from './ERC20.js';
export type { ERC721 } from './ERC721.js';
export type { HappyRedPacketV1 } from './HappyRedPacketV1.js';
export type { HappyRedPacketV2 } from './HappyRedPacketV2.js';
export type { HappyRedPacketV3 } from './HappyRedPacketV3.js';
export type { HappyRedPacketV4 } from './HappyRedPacketV4.js';
export type { NftRedPacket } from './NftRedPacket.js';
export type { WETH } from './WETH.js';
export type { Wallet } from './Wallet.js';
