/* cspell:disable */
import { EthereumChainId } from '@/web3-shared/evm/types.js';

export const DEBANK_CHAINS = [
    {
        id: 'eth',
        community_id: 1,
        name: 'Ethereum',
        native_token_id: 'eth',
        logo_url: '/image/chains/ethereum.png',
    },
    {
        id: 'bsc',
        community_id: 56,
        name: 'BSC',
        native_token_id: 'bsc',
        logo_url: '/image/chains/binance.png',
    },
    {
        id: 'xdai',
        community_id: 100,
        name: 'Gnosis',
        native_token_id: 'xdai',
        logo_url: '/image/chains/xdai.png',
    },
    {
        id: 'matic',
        community_id: 137,
        name: 'Polygon',
        native_token_id: 'matic',
        logo_url: '/image/chains/polygon.png',
    },
    {
        id: 'ftm',
        community_id: 250,
        name: 'Fantom',
        native_token_id: 'ftm',
        logo_url: '/image/chains/fantom.png',
    },
    {
        id: 'okt',
        community_id: 66,
        name: 'OEC',
        native_token_id: 'okt',
        logo_url: '/image/chains/okt.png',
    },
    {
        id: 'heco',
        community_id: 128,
        name: 'HECO',
        native_token_id: 'heco',
        logo_url: '/image/chains/heco.png',
    },
    {
        id: 'avax',
        community_id: 43114,
        name: 'Avalanche',
        native_token_id: 'avax',
        logo_url: '/image/chains/avalanche.png',
    },
    {
        id: 'op',
        community_id: 10,
        name: 'Optimism',
        native_token_id: 'op',
        logo_url: '/image/chains/optimism.png',
    },
    {
        id: 'arb',
        community_id: 42161,
        name: 'Arbitrum',
        native_token_id: 'arb',
        logo_url: '/image/chains/arbitrum.png',
    },
    {
        id: 'celo',
        community_id: 42220,
        name: 'Celo',
        native_token_id: 'celo',
        logo_url: '/image/chains/celo.png',
    },
    {
        id: 'movr',
        community_id: 1285,
        name: 'Moonriver',
        native_token_id: 'movr',
        logo_url: '/image/chains/movr.png',
    },
    {
        id: 'cro',
        community_id: 25,
        name: 'Cronos',
        native_token_id: 'cro',
        logo_url: '/image/chains/cro.png',
    },
    {
        id: 'boba',
        community_id: 288,
        name: 'Boba',
        native_token_id: 'boba',
        logo_url: '/image/chains/boba.png',
    },
    {
        id: 'metis',
        community_id: 1088,
        name: 'Metis',
        native_token_id: 'metis',
        logo_url: '/image/chains/metis.png',
    },
    {
        id: 'btt',
        community_id: 199,
        name: 'BitTorrent',
        native_token_id: 'btt',
        logo_url: '/image/chains/btt.png',
    },
    {
        id: 'aurora',
        community_id: 1313161554,
        name: 'Aurora',
        native_token_id: 'aurora',
        logo_url: '/image/chains/aurora.png',
    },
    {
        id: 'mobm',
        community_id: 1284,
        name: 'Moonbeam',
        native_token_id: 'mobm',
        logo_url: '/image/chains/moonbeam.png',
    },
    {
        id: 'sbch',
        community_id: 10000,
        name: 'SmartBch',
        native_token_id: 'sbch',
        logo_url: '/image/chains/sbch.png',
    },
    {
        id: 'fuse',
        community_id: 122,
        name: 'Fuse',
        native_token_id: 'fuse',
        logo_url: '/image/chains/fuse.png',
    },
    {
        id: 'lens',
        community_id: 232,
        name: 'GHO',
        native_token_id: 'lens',
        logo_url: '/image/chains/lens.png',
    },
    {
        id: 'hmy',
        community_id: 1666600000,
        name: 'Harmony',
        native_token_id: 'hmy',
        logo_url: '/image/chains/hmy.png',
    },
    {
        id: 'klay',
        community_id: 8217,
        name: 'Klaytn',
        native_token_id: 'klay',
        logo_url: '/image/chains/klay.png',
    },
    {
        id: 'astar',
        community_id: 592,
        name: 'Astar',
        native_token_id: 'astar',
        logo_url: '/image/chains/astar.png',
    },
    {
        id: 'sdn',
        community_id: 336,
        name: 'Shiden',
        native_token_id: 'sdn',
        logo_url: '/image/chains/sdn.png',
    },
    {
        id: 'palm',
        community_id: 11297108109,
        name: 'Palm',
        native_token_id: 'palm',
        logo_url: '/image/chains/palm.png',
    },
    {
        id: 'iotx',
        community_id: 4689,
        name: 'IoTeX',
        native_token_id: 'iotx',
        logo_url: '/image/chains/iotx.png',
    },
    {
        id: 'rsk',
        community_id: 30,
        name: 'RSK',
        native_token_id: 'rsk',
        logo_url: '/image/chains/rsk.png',
    },
    {
        id: 'wan',
        community_id: 888,
        name: 'Wanchain',
        native_token_id: 'wan',
        logo_url: '/image/chains/wan.png',
    },
    {
        id: 'kcc',
        community_id: 321,
        name: 'KCC',
        native_token_id: 'kcc',
        logo_url: '/image/chains/kcc.png',
    },
    {
        id: 'sgb',
        community_id: 19,
        name: 'Songbird',
        native_token_id: 'sgb',
        logo_url: '/image/chains/sgb.png',
    },
    {
        id: 'evmos',
        community_id: 9001,
        name: 'EvmOS',
        native_token_id: 'evmos',
        logo_url: '/image/chains/evmos.png',
    },
    {
        id: 'dfk',
        community_id: 53935,
        name: 'DFK',
        native_token_id: 'dfk',
        logo_url: '/image/chains/dfk.png',
    },
    {
        id: 'tlos',
        community_id: 40,
        name: 'Telos',
        native_token_id: 'tlos',
        logo_url: '/image/chains/telos.png',
    },
    {
        id: 'swm',
        community_id: 73772,
        name: 'Swimmer',
        native_token_id: 'swm',
        logo_url: '/image/chains/swm.png',
    },
    {
        id: 'nova',
        community_id: 42170,
        name: 'Arbitrum Nova',
        native_token_id: 'nova',
        logo_url: '/image/chains/arbitrum.png',
    },
    {
        id: 'canto',
        community_id: 7700,
        name: 'Canto',
        native_token_id: 'canto',
        logo_url: '/image/chains/canto.png',
    },
    {
        id: 'doge',
        community_id: 2000,
        name: 'Dogechain',
        native_token_id: 'doge',
        logo_url: '/image/chains/doge.png',
    },
    {
        id: 'kava',
        community_id: 2222,
        name: 'Kava',
        native_token_id: 'kava',
        logo_url: '/image/chains/kava.png',
    },
    {
        id: 'step',
        community_id: 1234,
        name: 'Step',
        native_token_id: 'step',
        logo_url: '/image/chains/step.png',
    },
    {
        id: 'mada',
        community_id: 2001,
        name: 'Milkomeda',
        native_token_id: 'mada',
        logo_url: '/image/chains/mada.png',
    },
    {
        id: 'cfx',
        community_id: 1030,
        name: 'Conflux',
        native_token_id: 'cfx',
        logo_url: '/image/chains/conflux.png',
    },
    {
        id: 'brise',
        community_id: 32520,
        name: 'Bitgert',
        native_token_id: 'brise',
        logo_url: '/image/chains/brise.png',
    },
    {
        id: 'base',
        community_id: 8453,
        name: 'Base',
        native_token_id: 'eth',
        logo_url: '/image/chains/base.png',
    },
    {
        id: 'metis',
        community_id: 1088,
        name: 'Metis',
        native_token_id: 'eth',
        logo_url: '/image/chains/metis.png',
    },
    {
        id: 'zora',
        community_id: 7777777,
        name: 'Zora',
        native_token_id: 'eth',
        logo_url: '/image/chains/zora.png',
    },
    {
        id: 'scrl',
        community_id: 534352,
        name: 'Scroll',
        native_token_id: 'eth',
        logo_url: '/image/chains/scroll.png',
    },
    {
        id: 'era',
        community_id: 324,
        name: 'ZKsync Era',
        native_token_id: 'eth',
        logo_url: '/image/chains/era.png',
    },
    {
        id: 'linea',
        community_id: 59_144,
        name: 'Linea',
        native_token_id: 'eth',
        logo_url: '/image/chains/linea.png',
    },
    {
        id: 'plasma',
        community_id: 9745,
        name: 'Plasma',
        native_token_id: 'xpl',
        logo_url: '/image/chains/plasma.png',
    },
];

export const DEBANK_CHAIN_TO_CHAIN_ID_MAP: Record<string, number> = {
    arb: EthereumChainId.Arbitrum,
    aurora: EthereumChainId.Aurora,
    avax: EthereumChainId.Avalanche,
    bsc: EthereumChainId.BSC,
    cfx: EthereumChainId.Conflux,
    eth: EthereumChainId.Mainnet,
    ftm: EthereumChainId.Fantom,
    matic: EthereumChainId.Polygon,
    metis: EthereumChainId.Metis,
    op: EthereumChainId.Optimism,
    xdai: EthereumChainId.xDai,
    base: EthereumChainId.Base,
    scrl: EthereumChainId.Scroll,
    lens: EthereumChainId.Lens,
    linea: EthereumChainId.Linea,
    era: EthereumChainId.ZksyncEra,
    celo: EthereumChainId.Celo,
    plasma: EthereumChainId.Plasma,
};
