import { Locale } from '@dimensiondev/enums';

export interface GameCountryEntry {
    /** FIFA country code, e.g. "ARG". */
    code: string;
    /** Polymarket team/country names (locale-independent identifiers) used to match raw team names. */
    pmNames: string[];
    /** Localized display names per app locale. */
    names: Record<Locale, string>;
}

/**
 * World Cup participating countries with localized names, baked in from
 * `GET /v1/fifa/countries`. The roster is fixed, so we ship it as a constant
 * instead of fetching it at runtime.
 */
export const GAME_COUNTRIES: GameCountryEntry[] = [
    {
        code: 'ALG',
        pmNames: ['Algeria', 'ALG'],
        names: {
            [Locale.en]: 'Algeria',
            [Locale.es]: 'Argelia',
            [Locale.ja]: 'アルジェリア',
            [Locale.ko]: '알제리',
            [Locale.zhHans]: '阿尔及利亚',
            [Locale.zhHant]: '阿爾及利亞',
        },
    },
    {
        code: 'ARG',
        pmNames: ['Argentina', 'ARG'],
        names: {
            [Locale.en]: 'Argentina',
            [Locale.es]: 'Argentina',
            [Locale.ja]: 'アルゼンチン',
            [Locale.ko]: '아르헨티나',
            [Locale.zhHans]: '阿根廷',
            [Locale.zhHant]: '阿根廷',
        },
    },
    {
        code: 'AUS',
        pmNames: ['Australia', 'AUS'],
        names: {
            [Locale.en]: 'Australia',
            [Locale.es]: 'Australia',
            [Locale.ja]: 'オーストラリア',
            [Locale.ko]: '호주',
            [Locale.zhHans]: '澳大利亚',
            [Locale.zhHant]: '澳洲',
        },
    },
    {
        code: 'AUT',
        pmNames: ['Austria', 'AUT'],
        names: {
            [Locale.en]: 'Austria',
            [Locale.es]: 'Austria',
            [Locale.ja]: 'オーストリア',
            [Locale.ko]: '오스트리아',
            [Locale.zhHans]: '奥地利',
            [Locale.zhHant]: '奧地利',
        },
    },
    {
        code: 'BEL',
        pmNames: ['Belgium', 'BEL'],
        names: {
            [Locale.en]: 'Belgium',
            [Locale.es]: 'Bélgica',
            [Locale.ja]: 'ベルギー',
            [Locale.ko]: '벨기에',
            [Locale.zhHans]: '比利时',
            [Locale.zhHant]: '比利時',
        },
    },
    {
        code: 'BIH',
        pmNames: ['Bosnia and Herzegovina', 'BIH', 'Bosnia-Herzegovina'],
        names: {
            [Locale.en]: 'Bosnia and Herzegovina',
            [Locale.es]: 'Bosnia y Herzegovina',
            [Locale.ja]: 'ボスニア・ヘルツェゴビナ',
            [Locale.ko]: '보스니아 헤르체고비나',
            [Locale.zhHans]: '波黑',
            [Locale.zhHant]: '波士尼亞與赫塞哥維納',
        },
    },
    {
        code: 'BRA',
        pmNames: ['Brazil', 'BRA'],
        names: {
            [Locale.en]: 'Brazil',
            [Locale.es]: 'Brasil',
            [Locale.ja]: 'ブラジル',
            [Locale.ko]: '브라질',
            [Locale.zhHans]: '巴西',
            [Locale.zhHant]: '巴西',
        },
    },
    {
        code: 'CPV',
        pmNames: ['Cabo Verde', 'CPV', 'Cape Verde'],
        names: {
            [Locale.en]: 'Cabo Verde',
            [Locale.es]: 'Cabo Verde',
            [Locale.ja]: 'カーボベルデ',
            [Locale.ko]: '카보베르데',
            [Locale.zhHans]: '佛得角',
            [Locale.zhHant]: '維德角',
        },
    },
    {
        code: 'CAN',
        pmNames: ['Canada', 'CAN'],
        names: {
            [Locale.en]: 'Canada',
            [Locale.es]: 'Canadá',
            [Locale.ja]: 'カナダ',
            [Locale.ko]: '캐나다',
            [Locale.zhHans]: '加拿大',
            [Locale.zhHant]: '加拿大',
        },
    },
    {
        code: 'COL',
        pmNames: ['Colombia', 'COL'],
        names: {
            [Locale.en]: 'Colombia',
            [Locale.es]: 'Colombia',
            [Locale.ja]: 'コロンビア',
            [Locale.ko]: '콜롬비아',
            [Locale.zhHans]: '哥伦比亚',
            [Locale.zhHant]: '哥倫比亞',
        },
    },
    {
        code: 'CIV',
        pmNames: ["Côte d'Ivoire", 'CIV', 'Ivory Coast'],
        names: {
            [Locale.en]: "Côte d'Ivoire",
            [Locale.es]: 'Costa de Marfil',
            [Locale.ja]: 'コートジボワール',
            [Locale.ko]: '코트디부아르',
            [Locale.zhHans]: '科特迪瓦',
            [Locale.zhHant]: '象牙海岸',
        },
    },
    {
        code: 'CRO',
        pmNames: ['Croatia', 'CRO'],
        names: {
            [Locale.en]: 'Croatia',
            [Locale.es]: 'Croacia',
            [Locale.ja]: 'クロアチア',
            [Locale.ko]: '크로아티아',
            [Locale.zhHans]: '克罗地亚',
            [Locale.zhHant]: '克羅埃西亞',
        },
    },
    {
        code: 'CUW',
        pmNames: ['Curaçao', 'CUW'],
        names: {
            [Locale.en]: 'Curaçao',
            [Locale.es]: 'Curazao',
            [Locale.ja]: 'キュラソー',
            [Locale.ko]: '퀴라소',
            [Locale.zhHans]: '库拉索',
            [Locale.zhHant]: '庫拉索',
        },
    },
    {
        code: 'CZE',
        pmNames: ['Czechia', 'CZE'],
        names: {
            [Locale.en]: 'Czechia',
            [Locale.es]: 'Chequia',
            [Locale.ja]: 'チェコ',
            [Locale.ko]: '체코',
            [Locale.zhHans]: '捷克',
            [Locale.zhHant]: '捷克',
        },
    },
    {
        code: 'CGO',
        pmNames: ['DR Congo', 'CGO', 'Congo DR'],
        names: {
            [Locale.en]: 'DR Congo',
            [Locale.es]: 'RD del Congo',
            [Locale.ja]: 'コンゴ民主共和国',
            [Locale.ko]: '콩고 DR',
            [Locale.zhHans]: '刚果金',
            [Locale.zhHant]: '剛果金',
        },
    },
    {
        code: 'ECU',
        pmNames: ['Ecuador', 'ECU'],
        names: {
            [Locale.en]: 'Ecuador',
            [Locale.es]: 'Ecuador',
            [Locale.ja]: 'エクアドル',
            [Locale.ko]: '에콰도르',
            [Locale.zhHans]: '厄瓜多尔',
            [Locale.zhHant]: '厄瓜多',
        },
    },
    {
        code: 'EGY',
        pmNames: ['Egypt', 'EGY'],
        names: {
            [Locale.en]: 'Egypt',
            [Locale.es]: 'Egipto',
            [Locale.ja]: 'エジプト',
            [Locale.ko]: '이집트',
            [Locale.zhHans]: '埃及',
            [Locale.zhHant]: '埃及',
        },
    },
    {
        code: 'ENG',
        pmNames: ['England', 'ENG'],
        names: {
            [Locale.en]: 'England',
            [Locale.es]: 'Inglaterra',
            [Locale.ja]: 'イングランド',
            [Locale.ko]: '잉글랜드',
            [Locale.zhHans]: '英格兰',
            [Locale.zhHant]: '英格蘭',
        },
    },
    {
        code: 'FRA',
        pmNames: ['France', 'FRA'],
        names: {
            [Locale.en]: 'France',
            [Locale.es]: 'Francia',
            [Locale.ja]: 'フランス',
            [Locale.ko]: '프랑스',
            [Locale.zhHans]: '法国',
            [Locale.zhHant]: '法國',
        },
    },
    {
        code: 'GER',
        pmNames: ['Germany', 'GER'],
        names: {
            [Locale.en]: 'Germany',
            [Locale.es]: 'Alemania',
            [Locale.ja]: 'ドイツ',
            [Locale.ko]: '독일',
            [Locale.zhHans]: '德国',
            [Locale.zhHant]: '德國',
        },
    },
    {
        code: 'GHA',
        pmNames: ['Ghana', 'GHA'],
        names: {
            [Locale.en]: 'Ghana',
            [Locale.es]: 'Ghana',
            [Locale.ja]: 'ガーナ',
            [Locale.ko]: '가나',
            [Locale.zhHans]: '加纳',
            [Locale.zhHant]: '迦納',
        },
    },
    {
        code: 'HAI',
        pmNames: ['Haiti', 'HAI'],
        names: {
            [Locale.en]: 'Haiti',
            [Locale.es]: 'Haití',
            [Locale.ja]: 'ハイチ',
            [Locale.ko]: '아이티',
            [Locale.zhHans]: '海地',
            [Locale.zhHant]: '海地',
        },
    },
    {
        code: 'IRQ',
        pmNames: ['Iraq', 'IRQ'],
        names: {
            [Locale.en]: 'Iraq',
            [Locale.es]: 'Irak',
            [Locale.ja]: 'イラク',
            [Locale.ko]: '이라크',
            [Locale.zhHans]: '伊拉克',
            [Locale.zhHant]: '伊拉克',
        },
    },
    {
        code: 'IRN',
        pmNames: ['IR Iran', 'IRN', 'Iran'],
        names: {
            [Locale.en]: 'IR Iran',
            [Locale.es]: 'Irán',
            [Locale.ja]: 'イラン',
            [Locale.ko]: '이란',
            [Locale.zhHans]: '伊朗',
            [Locale.zhHant]: '伊朗',
        },
    },
    {
        code: 'JPN',
        pmNames: ['Japan', 'JPN'],
        names: {
            [Locale.en]: 'Japan',
            [Locale.es]: 'Japón',
            [Locale.ja]: '日本',
            [Locale.ko]: '일본',
            [Locale.zhHans]: '日本',
            [Locale.zhHant]: '日本',
        },
    },
    {
        code: 'JOR',
        pmNames: ['Jordan', 'JOR'],
        names: {
            [Locale.en]: 'Jordan',
            [Locale.es]: 'Jordania',
            [Locale.ja]: 'ヨルダン',
            [Locale.ko]: '요르단',
            [Locale.zhHans]: '约旦',
            [Locale.zhHant]: '約旦',
        },
    },
    {
        code: 'KOR',
        pmNames: ['Korea Republic', 'KOR', 'South Korea'],
        names: {
            [Locale.en]: 'Korea Republic',
            [Locale.es]: 'Corea del Sur',
            [Locale.ja]: '韓国',
            [Locale.ko]: '대한민국',
            [Locale.zhHans]: '韩国',
            [Locale.zhHant]: '南韓',
        },
    },
    {
        code: 'MEX',
        pmNames: ['Mexico', 'MEX'],
        names: {
            [Locale.en]: 'Mexico',
            [Locale.es]: 'México',
            [Locale.ja]: 'メキシコ',
            [Locale.ko]: '멕시코',
            [Locale.zhHans]: '墨西哥',
            [Locale.zhHant]: '墨西哥',
        },
    },
    {
        code: 'MAR',
        pmNames: ['Morocco', 'MAR'],
        names: {
            [Locale.en]: 'Morocco',
            [Locale.es]: 'Marruecos',
            [Locale.ja]: 'モロッコ',
            [Locale.ko]: '모로코',
            [Locale.zhHans]: '摩洛哥',
            [Locale.zhHant]: '摩洛哥',
        },
    },
    {
        code: 'NED',
        pmNames: ['Netherlands', 'NED'],
        names: {
            [Locale.en]: 'Netherlands',
            [Locale.es]: 'Países Bajos',
            [Locale.ja]: 'オランダ',
            [Locale.ko]: '네덜란드',
            [Locale.zhHans]: '荷兰',
            [Locale.zhHant]: '荷蘭',
        },
    },
    {
        code: 'NZL',
        pmNames: ['New Zealand', 'NZL'],
        names: {
            [Locale.en]: 'New Zealand',
            [Locale.es]: 'Nueva Zelanda',
            [Locale.ja]: 'ニュージーランド',
            [Locale.ko]: '뉴질랜드',
            [Locale.zhHans]: '新西兰',
            [Locale.zhHant]: '紐西蘭',
        },
    },
    {
        code: 'NOR',
        pmNames: ['Norway', 'NOR'],
        names: {
            [Locale.en]: 'Norway',
            [Locale.es]: 'Noruega',
            [Locale.ja]: 'ノルウェー',
            [Locale.ko]: '노르웨이',
            [Locale.zhHans]: '挪威',
            [Locale.zhHant]: '挪威',
        },
    },
    {
        code: 'PAN',
        pmNames: ['Panama', 'PAN'],
        names: {
            [Locale.en]: 'Panama',
            [Locale.es]: 'Panamá',
            [Locale.ja]: 'パナマ',
            [Locale.ko]: '파나마',
            [Locale.zhHans]: '巴拿马',
            [Locale.zhHant]: '巴拿馬',
        },
    },
    {
        code: 'PAR',
        pmNames: ['Paraguay', 'PAR'],
        names: {
            [Locale.en]: 'Paraguay',
            [Locale.es]: 'Paraguay',
            [Locale.ja]: 'パラグアイ',
            [Locale.ko]: '파라과이',
            [Locale.zhHans]: '巴拉圭',
            [Locale.zhHant]: '巴拉圭',
        },
    },
    {
        code: 'POR',
        pmNames: ['Portugal', 'POR'],
        names: {
            [Locale.en]: 'Portugal',
            [Locale.es]: 'Portugal',
            [Locale.ja]: 'ポルトガル',
            [Locale.ko]: '포르투갈',
            [Locale.zhHans]: '葡萄牙',
            [Locale.zhHant]: '葡萄牙',
        },
    },
    {
        code: 'QAT',
        pmNames: ['Qatar', 'QAT'],
        names: {
            [Locale.en]: 'Qatar',
            [Locale.es]: 'Catar',
            [Locale.ja]: 'カタール',
            [Locale.ko]: '카타르',
            [Locale.zhHans]: '卡塔尔',
            [Locale.zhHant]: '卡達',
        },
    },
    {
        code: 'KSA',
        pmNames: ['Saudi Arabia', 'KSA'],
        names: {
            [Locale.en]: 'Saudi Arabia',
            [Locale.es]: 'Arabia Saudita',
            [Locale.ja]: 'サウジアラビア',
            [Locale.ko]: '사우디아라비아',
            [Locale.zhHans]: '沙特阿拉伯',
            [Locale.zhHant]: '沙烏地阿拉伯',
        },
    },
    {
        code: 'SCO',
        pmNames: ['Scotland', 'SCO'],
        names: {
            [Locale.en]: 'Scotland',
            [Locale.es]: 'Escocia',
            [Locale.ja]: 'スコットランド',
            [Locale.ko]: '스코틀랜드',
            [Locale.zhHans]: '苏格兰',
            [Locale.zhHant]: '蘇格蘭',
        },
    },
    {
        code: 'SEN',
        pmNames: ['Senegal', 'SEN'],
        names: {
            [Locale.en]: 'Senegal',
            [Locale.es]: 'Senegal',
            [Locale.ja]: 'セネガル',
            [Locale.ko]: '세네갈',
            [Locale.zhHans]: '塞内加尔',
            [Locale.zhHant]: '塞內加爾',
        },
    },
    {
        code: 'RSA',
        pmNames: ['South Africa', 'RSA'],
        names: {
            [Locale.en]: 'South Africa',
            [Locale.es]: 'Sudáfrica',
            [Locale.ja]: '南アフリカ',
            [Locale.ko]: '남아프리카',
            [Locale.zhHans]: '南非',
            [Locale.zhHant]: '南非',
        },
    },
    {
        code: 'ESP',
        pmNames: ['Spain', 'ESP'],
        names: {
            [Locale.en]: 'Spain',
            [Locale.es]: 'España',
            [Locale.ja]: 'スペイン',
            [Locale.ko]: '스페인',
            [Locale.zhHans]: '西班牙',
            [Locale.zhHant]: '西班牙',
        },
    },
    {
        code: 'SWE',
        pmNames: ['Sweden', 'SWE'],
        names: {
            [Locale.en]: 'Sweden',
            [Locale.es]: 'Suecia',
            [Locale.ja]: 'スウェーデン',
            [Locale.ko]: '스웨덴',
            [Locale.zhHans]: '瑞典',
            [Locale.zhHant]: '瑞典',
        },
    },
    {
        code: 'SUI',
        pmNames: ['Switzerland', 'SUI'],
        names: {
            [Locale.en]: 'Switzerland',
            [Locale.es]: 'Suiza',
            [Locale.ja]: 'スイス',
            [Locale.ko]: '스위스',
            [Locale.zhHans]: '瑞士',
            [Locale.zhHant]: '瑞士',
        },
    },
    {
        code: 'TUN',
        pmNames: ['Tunisia', 'TUN'],
        names: {
            [Locale.en]: 'Tunisia',
            [Locale.es]: 'Túnez',
            [Locale.ja]: 'チュニジア',
            [Locale.ko]: '튀니지',
            [Locale.zhHans]: '突尼斯',
            [Locale.zhHant]: '突尼斯',
        },
    },
    {
        code: 'TUR',
        pmNames: ['Türkiye', 'TUR', 'Turkiye'],
        names: {
            [Locale.en]: 'Türkiye',
            [Locale.es]: 'Turquía',
            [Locale.ja]: 'トルコ',
            [Locale.ko]: '튀르키예',
            [Locale.zhHans]: '土耳其',
            [Locale.zhHant]: '土耳其',
        },
    },
    {
        code: 'USA',
        pmNames: ['United States', 'USA'],
        names: {
            [Locale.en]: 'United States',
            [Locale.es]: 'Estados Unidos',
            [Locale.ja]: 'アメリカ',
            [Locale.ko]: '미국',
            [Locale.zhHans]: '美国',
            [Locale.zhHant]: '美國',
        },
    },
    {
        code: 'URU',
        pmNames: ['Uruguay', 'URU'],
        names: {
            [Locale.en]: 'Uruguay',
            [Locale.es]: 'Uruguay',
            [Locale.ja]: 'ウルグアイ',
            [Locale.ko]: '우루과이',
            [Locale.zhHans]: '乌拉圭',
            [Locale.zhHant]: '烏拉圭',
        },
    },
    {
        code: 'UZB',
        pmNames: ['Uzbekistan', 'UZB'],
        names: {
            [Locale.en]: 'Uzbekistan',
            [Locale.es]: 'Uzbekistán',
            [Locale.ja]: 'ウズベキスタン',
            [Locale.ko]: '우즈베키스탄',
            [Locale.zhHans]: '乌兹别克斯坦',
            [Locale.zhHant]: '烏茲別克',
        },
    },
];
