import {
    arbitrum,
    aurora,
    avalanche,
    base,
    blast,
    bsc,
    celo,
    confluxESpace,
    fantom,
    gnosis,
    lens,
    linea,
    mainnet,
    mantle,
    metis,
    optimism,
    plasma,
    polygon,
    scroll,
    xLayer,
    zkSync,
    zora,
} from 'viem/chains';

const COINGECKO_PLATFORM_ID = {
    Mainnet: 'ethereum',
    BSC: 'binance-smart-chain',
    Base: 'base',
    Polygon: 'polygon-pos',
    Arbitrum: 'arbitrum-one',
    xDai: 'xdai',
    Optimism: 'optimistic-ethereum',
    Avalanche: 'avalanche',
    Celo: 'celo',
    Fantom: 'fantom',
    Aurora: 'aurora',
    Astar: 'astar',
    Boba: 'boba',
    Metis: 'metis-andromeda',
    Scroll: 'scroll',
    Linea: 'linea',
    BitTorrent: 'bittorrent',
    Harmony: 'harmony-shard-0',
};

const COINGECKO_COIN_ID = {
    Mainnet: 'ethereum',
    BSC: 'binancecoin',
    Base: 'ethereum',
    Polygon: 'polygon-ecosystem-token',
    Arbitrum: 'ethereum',
    xDai: 'xdai',
    Optimism: 'ethereum',
    Avalanche: 'avalanche-2',
    Celo: 'celo',
    Fantom: 'fantom',
    Aurora: 'ethereum',
    Conflux: 'conflux-token',
    Astar: 'astar',
    Pulse: 'pulsechain',
    Moonbeam: 'moonbeam',
    Klaytn: 'klay-token',
    Harmony: 'harmony',
    Moonriver: 'moonriver',
    Cronos: 'crypto-com-chain',
    BitTorrent: 'bittorrent',
    Boba: 'boba-network',
    Metis: 'metis-token',
    Scroll: 'ethereum',
    Linea: 'ethereum',
    ZksyncEra: 'ethereum',
};

const COINGECKO_NETWORK_BY_CHAIN_ID: Record<number, string> = {
    [mainnet.id]: 'Mainnet',
    [base.id]: 'Base',
    [bsc.id]: 'BSC',
    [polygon.id]: 'Polygon',
    [optimism.id]: 'Optimism',
    [arbitrum.id]: 'Arbitrum',
    [gnosis.id]: 'xDai',
    [avalanche.id]: 'Avalanche',
    [aurora.id]: 'Aurora',
    [confluxESpace.id]: 'Conflux',
    [fantom.id]: 'Fantom',
    [xLayer.id]: 'XLayer',
    [metis.id]: 'Metis',
    [mantle.id]: 'Mantle',
    [zora.id]: 'Zora',
    [scroll.id]: 'Scroll',
    [celo.id]: 'Celo',
    [lens.id]: 'Lens',
    [zkSync.id]: 'ZksyncEra',
    [linea.id]: 'Linea',
    [plasma.id]: 'Plasma',
    [blast.id]: 'Blast',
};

export function getCoinGeckoConstants(chainId: number) {
    const chainName = COINGECKO_NETWORK_BY_CHAIN_ID[chainId];
    if (!chainName) return {} as { PLATFORM_ID?: string; COIN_ID?: string };

    return {
        PLATFORM_ID: COINGECKO_PLATFORM_ID[chainName as keyof typeof COINGECKO_PLATFORM_ID] || '',
        COIN_ID: COINGECKO_COIN_ID[chainName as keyof typeof COINGECKO_COIN_ID] || '',
    };
}
