import {
    arbitrum,
    aurora,
    avalanche,
    base,
    blast,
    bsc,
    celo,
    confluxESpace,
    fantom,
    gnosis,
    lens,
    linea,
    mainnet,
    mantle,
    metis,
    optimism,
    plasma,
    polygon,
    scroll,
    xLayer,
    zkSync,
    zora,
} from 'viem/chains';

export const ETHEREUM_CHAIN_IDS = [
    mainnet.id,
    base.id,
    bsc.id,
    polygon.id,
    optimism.id,
    arbitrum.id,
    gnosis.id,
    avalanche.id,
    aurora.id,
    confluxESpace.id,
    fantom.id,
    xLayer.id,
    metis.id,
    mantle.id,
    zora.id,
    scroll.id,
    celo.id,
    lens.id,
    zkSync.id,
    linea.id,
    plasma.id,
    blast.id,
] as const;

export const USDC_E_POLYGON_ADDRESS = '0x2791bca1f2de4661ed88a30c99a7a9449aa84174';

export const SUPPORTED_SWAP_EVM_CHAIN_IDS = [1, 56, 137, 10, 8453, 42161, 43114, 81457, 534352] as const;
