name: Generate Sitemap

on:
    workflow_dispatch:

jobs:
    generate-sitemap:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.node-version'

            - uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install

            - name: Generate sitemap
              run: npm run build:sitemap

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  branch_name="sitemap/update-$(date +%s)"
                  git checkout -b $branch_name

                  if [[ $(git status --porcelain public/sitemap) ]]; then
                    git add public/sitemap
                    git commit -m "chore: update sitemap [bot]"
                    git push origin $branch_name
                    echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
                  else
                    echo "No changes to commit."
                    echo "SKIP_PR=true" >> $GITHUB_ENV
                  fi

            - name: Create Pull Request
              if: env.SKIP_PR != 'true'
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ env.BRANCH_NAME }}
                  base: main
                  title: 'chore: update sitemap'
                  body: 'Automated sitemap generation via GitHub Actions.'
                  labels: 'automated'
