name: CSpell

on:
    push:
        branches:
            - '**'
            - '!main'
            - '!released'

jobs:
    spellcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.node-version'

            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true

            - name: Setup Github Actions
              run: ./scripts/setup-gh-actions.sh

            - name: Run CSpell
              run: npx cspell --no-progress "**/*"
