name: ESLint

on:
    push:
        branches:
            - '**'
            - '!main'
            - '!released'
    workflow_dispatch:

concurrency:
    group: eslint
    cancel-in-progress: false

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.node-version'

            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true

            - name: Setup Github Actions
              run: ./scripts/setup-gh-actions.sh

            - name: Run ESLint
              run: NODE_OPTIONS=--max_old_space_size=8192 npx eslint . --quiet --cache --cache-location .eslintcache
