name: Generate Package Analysis

on:
    pull_request:
        paths:
            - 'package.json'
            - 'apps/web/package.json'
            - 'pnpm-lock.yaml'
    workflow_dispatch:

jobs:
    regenerate-package-analysis:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.node-version'

            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true

            - name: Setup Github Actions
              run: .github/scripts/setup.sh

            - name: Generate Package Analysis
              run: node .github/scripts/generate-package-analysis.mjs

            - name: Commit and Push changes if necessary
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  if [[ $(git status --porcelain) ]]; then
                    git add apps/web/docs/PACKAGE_ANALYSIS.txt
                    git commit -m "chore: regenerate PACKAGE_ANALYSIS.txt [bot]"
                    git push origin HEAD:${{ github.event.pull_request.head.ref }}
                  else
                    echo "No changes to commit."
                  fi
