name: Maintenance

on:
    push:
        branches:
            - '**'
            - '!main'
            - '!released'
    workflow_dispatch:

jobs:
    maintenance:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.node-version'

            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true

            - name: Setup Github Actions
              run: .github/scripts/setup.sh

            - name: Run Lingui
              run: pnpm -r --filter='./apps/*' run lingui

            - name: Run Prettier
              run: npx prettier . -w

            - name: Run ESLint
              run: |
                  npx eslint --fix . || echo "ESLint completed with warnings"

            - name: Generate Package Analysis
              run: node .github/scripts/generate-package-analysis.mjs

            - name: Commit and Push changes if necessary
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  if [[ $(git status --porcelain) ]]; then
                    git add ./
                    git commit -m "chore: code maintenance [bot]"
                    git push origin
                  else
                    echo "No changes to commit."
                  fi
